import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const source='https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers';
const keys=['q','letter','town','county','route','rating'];
function readFilters(){const p=new URLSearchParams(location.search);return Object.fromEntries(keys.map(k=>[k,p.get(k)||'']));}
const empty=Object.fromEntries(keys.map(k=>[k,'']));
function App(){
 const [filters,setFilters]=useState(readFilters),[manifest,setManifest]=useState(null),[options,setOptions]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(true),[retry,setRetry]=useState(0),[detail,setDetail]=useState(null);
 const worker=useRef(),request=useRef(0),detailRequest=useRef(0);
 useEffect(()=>{const back=()=>{setFilters(readFilters());setPage(1);};addEventListener('popstate',back);return()=>removeEventListener('popstate',back);},[]);
 useEffect(()=>{let cancelled=false;const controller=new AbortController();setError('');setOptions(null);setBusy(true);
 const w=new Worker(new URL('./search.worker.js',import.meta.url),{type:'module'});worker.current=w;
 w.onmessage=({data})=>{if(cancelled)return;if(data.type==='ready')setOptions(data.options);if(data.type==='error'&&(data.id===undefined||data.id===request.current)){setError(data.message);setBusy(false);}if(data.type==='results'&&data.id===request.current){setResult(data);setError('');setBusy(false);}};
 w.onerror=()=>{setError('搜索服务未能启动，请重试。');setBusy(false);};
 fetch('/data/manifest.json',{cache:'no-cache',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('数据暂时不可用');return r.json();}).then(m=>{if(cancelled)return;setManifest(m);w.postMessage({type:'init',manifest:m});}).catch(e=>{if(!cancelled){setError('暂时无法加载名录，请检查网络后重试。');setBusy(false);}});
 return()=>{cancelled=true;controller.abort();w.terminate();};},[retry]);
 useEffect(()=>{if(!options)return;setBusy(true);const id=++request.current;const timer=setTimeout(()=>{worker.current.postMessage({type:'search',id,filters,page});},180);return()=>clearTimeout(timer);},[filters,page,options]);
 function change(key,value){setFilters(f=>{const next={...f,[key]:value};saveUrl(next);return next;});setPage(1);setDetail(null);detailRequest.current++;}
 function saveUrl(f){const p=new URLSearchParams();keys.forEach(k=>{if(f[k])p.set(k,f[k]);});history.replaceState(null,'',location.pathname+(p.size?'?'+p:''));}
 function clear(){setFilters({...empty});saveUrl(empty);setPage(1);setDetail(null);detailRequest.current++;}
 function expand(row){setDetail(current=>current?.id===row.id?null:row);}
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_sponsor_results',description:'Read the currently visible sponsor search results and active filters.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('No arguments accepted');return {loading:busy,error,filters,total:result?.total??null,records:result?.rows??[]};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[result,filters,busy,error]);
 const date=s=>s?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeZone:'Europe/London'}).format(new Date(s)):'—';
 return <><header><a className="brand" href="/">英才通<span>SPONSORFIND</span></a></header><main><section className="intro"><div><span className="eyebrow">英国签证赞助机构查询</span><h1>下一站，<em>英国机遇。</em></h1><p>发现英国签证赞助雇主，从一份清晰的名录开始。</p></div><div className="source-note"><span className="dot"/> GOV.UK 公开名录<br/><small>政府更新：{date(manifest?.source_updated)}<br/>本站检查：{date(manifest?.checked_at)}</small></div></section>
 <section className="search-panel" aria-label="查询条件"><label className="search-label" htmlFor="query">寻找公司或机构</label><div className="search-box"><span aria-hidden="true">⌕</span><input id="query" type="search" value={filters.q} placeholder="输入英文公司名称或关键词…" onChange={e=>change('q',e.target.value)}/></div><div className="filters">{[['town','城镇 / 城市'],['county','县 / 地区'],['route','签证路线'],['rating','赞助类型与评级']].map(([key,label])=><label key={key}>{label}<select value={filters[key]} onChange={e=>change(key,e.target.value)} disabled={!options}><option value="">全部</option>{filters[key]&&!options?.[key]?.includes(filters[key])&&<option value={filters[key]}>{filters[key]}</option>}{options?.[key]?.map(v=><option key={v}>{v}</option>)}</select></label>)}</div><div className="letters" aria-label="按首字母浏览">{[['','全部'],...'abcdefghijklmnopqrstuvwxyz'.split('').map(x=>[x,x.toUpperCase()]),['0-9','0–9'],['other','其他']].map(([key,label])=><button key={key} aria-pressed={filters.letter===key} onClick={()=>change('letter',key)}>{label}</button>)}</div></section>
 <div className="results-heading"><h2>探索赞助机构 <span>{result?result.total.toLocaleString():'—'} 条记录</span></h2><button className="text-button" onClick={clear}>清空筛选</button></div><p className="notice">持有赞助资质不代表正在招聘或承诺提供签证赞助。同一机构可能有多条许可记录。</p>
 {keys.some(k=>filters[k])&&<div className="active-filters">{keys.filter(k=>filters[k]).map(k=><button key={k} onClick={()=>change(k,'')}>{filters[k]} ×</button>)}</div>}
 <section aria-label="查询结果" aria-busy={busy}><div role="status" className="status">{busy?'正在查询名录…':''}</div>{error?<div className="empty" role="alert">{error}<button onClick={()=>setRetry(x=>x+1)}>重新加载</button></div>:<><div className="cards">{result?.rows.map(row=><article key={row.id}><div className="card-top"><div><h3>{row.name}</h3><p className="location">{row.town||'城市未提供'} · {row.county||'县 / 地区未提供'}</p></div><button className="detail-button" aria-expanded={detail?.id===row.id} onClick={()=>expand(row)}>{detail?.id===row.id?'收起 −':'详情 ＋'}</button></div><div className="tags"><span>{row.route||'路线未提供'}</span><span className="rating">{row.rating||'评级未提供'}</span></div>{detail?.id===row.id&&<div className="detail">{detail.loading?'正在加载详情…':detail.error?<span>详情加载失败。<button onClick={()=>{setDetail(null);detailRequest.current++;}}>关闭后重试</button></span>:<><dl>{[['机构名称',detail.name],['城镇 / 城市',detail.town],['县 / 地区',detail.county],['签证路线',detail.route],['赞助类型与评级',detail.rating]].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v||'未提供'}</dd></React.Fragment>)}</dl><a href={source} target="_blank" rel="noreferrer">查看政府名录发布页面 ↗</a></>}</div>}</article>)}</div>{result?.total===0&&!busy&&<div className="empty">没有找到匹配的机构。试试更短的英文关键词，或减少筛选条件。</div>}{result&&result.total>0&&<nav className="pagination" aria-label="结果分页"><button disabled={busy||result.page<=1} onClick={()=>setPage(result.page-1)}>← 上一页</button><span>{result.page} / {result.pages}</span><button disabled={busy||result.page>=result.pages} onClick={()=>setPage(result.page+1)}>下一页 →</button></nav>}</>}</section>
 <footer><strong>英才通</strong><p>数据来源：UK Visas and Immigration · 本站为独立查询工具，与英国政府无隶属关系。</p><p>Contains public sector information licensed under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" target="_blank" rel="noreferrer">Open Government Licence v3.0</a>.</p></footer></main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
